openapi: 3.0.3
info:
  title: Dubhu Designer API
  description: API specification for Dubhu Designer services.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

tags:
  - name: Tools
  - name: Instructions
  - name: Concierges
  - name: Agents
  - name: Variables
  - name: Environments

paths:
  /tools:
    $ref: './paths/tools.yaml#/~1tools'
  /tools/{toolId}/usages:
    $ref: './paths/tools.yaml#/~1tools~1{toolId}~1usages'
  /tools/{toolId}:
    $ref: './paths/tools.yaml#/~1tools~1{toolId}'
  /instructions:
    $ref: './paths/instructions.yaml#/~1instructions'
  /instructions/{instructionId}/usages:
    $ref: './paths/instructions.yaml#/~1instructions~1{instructionId}~1usages'
  /instructions/{instructionId}:
    $ref: './paths/instructions.yaml#/~1instructions~1{instructionId}'
  /concierges:
    $ref: './paths/concierges.yaml#/~1concierges'
  /concierges/{conciergeId}:
    $ref: './paths/concierges.yaml#/~1concierges~1{conciergeId}'
  /concierge/{conciergeId}:save:
    $ref: './paths/concierges.yaml#/~1concierge~1{conciergeId}:save'
  /concierges/{conciergeId}/concierge-versions/{conciergeVersionId}:
    $ref: './paths/concierges.yaml#/~1concierges~1{conciergeId}~1concierge-versions~1{conciergeVersionId}'
  /concierges/{conciergeId}/concierge-versions/{conciergeVersionId}/agents:
    $ref: './paths/agents.yaml#/~1concierges~1{conciergeId}~1concierge-versions~1{conciergeVersionId}~1agents'
  /concierges/{conciergeId}/concierge-versions/{conciergeVersionId}/agents/{agentId}:
    $ref: './paths/agents.yaml#/~1concierges~1{conciergeId}~1concierge-versions~1{conciergeVersionId}~1agents~1{agentId}'
  /concierges/{conciergeId}/concierge-versions/{conciergeVersionId}/agents/{agentId}/instructions/{instructionId}:
    $ref: './paths/agents.yaml#/~1concierges~1{conciergeId}~1concierge-versions~1{conciergeVersionId}~1agents~1{agentId}~1instructions~1{instructionId}'
  /concierges/{conciergeId}/concierge-versions/{conciergeVersionId}/agents/{agentId}/tools/{toolId}:
    $ref: './paths/agents.yaml#/~1concierges~1{conciergeId}~1concierge-versions~1{conciergeVersionId}~1agents~1{agentId}~1tools~1{toolId}'
  /variables:
    $ref: './paths/variables.yaml#/~1variables'
  /variables/{variableId}:
    $ref: './paths/variables.yaml#/~1variables~1{variableId}'
  /environments:
    $ref: './paths/environments.yaml#/~1environments'
  /environments/{environmentId}:
    $ref: './paths/environments.yaml#/~1environments~1{environmentId}'

components:
  schemas:
    ToolInput:
      $ref: './schemas/tools.yaml#/ToolInput'
    ToolOutput:
      $ref: './schemas/tools.yaml#/ToolOutput'
    CreateToolRequest:
      $ref: './schemas/tools.yaml#/CreateToolRequest'
    UpdateToolRequest:
      $ref: './schemas/tools.yaml#/UpdateToolRequest'
    Tool:
      $ref: './schemas/tools.yaml#/Tool'
    ToolUsage:
      $ref: './schemas/tools.yaml#/ToolUsage'
    CreateInstructionRequest:
      $ref: './schemas/instructions.yaml#/CreateInstructionRequest'
    UpdateInstructionRequest:
      $ref: './schemas/instructions.yaml#/UpdateInstructionRequest'
    InstructionUsage:
      $ref: './schemas/instructions.yaml#/InstructionUsage'
    InstructionSummary:
      $ref: './schemas/instructions.yaml#/InstructionSummary'
    Instruction:
      $ref: './schemas/instructions.yaml#/Instruction'
    CreateConciergeRequest:
      $ref: './schemas/concierges.yaml#/CreateConciergeRequest'
    ConciergeSummary:
      $ref: './schemas/concierges.yaml#/ConciergeSummary'
    Concierge:
      $ref: './schemas/concierges.yaml#/Concierge'
    SavedConciergeVersion:
      $ref: './schemas/concierges.yaml#/SavedConciergeVersion'
    ConciergeVersionDescriptor:
      $ref: './schemas/concierges.yaml#/ConciergeVersionDescriptor'
    SavedAgent:
      $ref: './schemas/concierges.yaml#/SavedAgent'
    SavedInstruction:
      $ref: './schemas/concierges.yaml#/SavedInstruction'
    CreateAgentRequest:
      $ref: './schemas/agents.yaml#/CreateAgentRequest'
    UpdateAgentRequest:
      $ref: './schemas/agents.yaml#/UpdateAgentRequest'
    Agent:
      $ref: './schemas/agents.yaml#/Agent'
    AgentSummary:
      $ref: './schemas/agents.yaml#/AgentSummary'
    VariableRequest:
      $ref: './schemas/variables.yaml#/VariableRequest'
    Variable:
      $ref: './schemas/variables.yaml#/Variable'
    EnvironmentRequest:
      $ref: './schemas/environments.yaml#/EnvironmentRequest'
    Environment:
      $ref: './schemas/environments.yaml#/Environment'
    FieldError:
      $ref: './schemas/common.yaml#/FieldError'
    ErrorResponse:
      $ref: './schemas/common.yaml#/ErrorResponse'
